[package]
name = "sindri-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
openapi = { path = "../openapi" }
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.11.27", features = ["json", "multipart"]}
reqwest-middleware = "0.2.0"
serde_json = "^1.0"
task-local-extensions = "0.1.4"
async-trait = "0.1.83"
