[package]
name = "sindri-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
openapi = { path = "../openapi" }
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.12.9", features = ["json", "multipart"]}
reqwest-middleware = "0.3.0"
reqwest-retry = "0.7.0"
serde_json = "^1.0"
async-trait = "0.1.83"
http = "1.2.0"
tracing = "0.1.41"
