[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
sindri-rs = { path = "../sindri-rs" }
tokio = { version = "1.42.0", features = ["full"] }
openapi = { path = "../openapi" }
env_logger = "0.9"
tracing-subscriber = "0.3"
tracing = "0.1"
