version: "3.9"

services:
  sindri-rust:
    image: rust:bookworm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace
      - cargo:/root/.cargo
      - git:/usr/local/cargo/git
      - npm:/root/.npm
      - registry:/usr/local/cargo/registry
      - rustup:/usr/local/rustup
      - sp1:/root/.sp1
      - target:/workspace/target
    working_dir: /workspace
    environment:
      - SINDRI_API_KEY=${SINDRI_API_KEY:-}
      - SINDRI_BASE_URL=${SINDRI_BASE_URL:-}
    command: ["sleep", "infinity"]
    stop_signal: SIGKILL

volumes:
  cargo:
  git:
  npm:
  registry:
  rustup:
  sp1:
  target:
