version: "3.9"

services:
  sindri-rust:
    image: rust:bookworm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace
      - git:/usr/local/cargo/git
      - registry:/usr/local/cargo/registry
      - rustup:/usr/local/rustup
      - sp1:/root/.sp1
      - target:/workspace/target
    working_dir: /workspace
    command: ["sleep", "infinity"]
    stop_signal: SIGKILL

volumes:
  git:
  registry:
  rustup:
  sp1:
  target:
