/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionResponse : Generic response for any client action. E.g. job submission, patch, delete
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ActionResponse {
    /// Generic response for any client action. E.g. job submission, patch, delete
    pub fn new() -> ActionResponse {
        ActionResponse {
            success: None,
        }
    }
}

