/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiKeyResponse : Response containing an API key.  This key is used in conjunction with the APIKey model to authenticate users in the API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponse {
    /// The API key. Will be `null` unless the key was created during the request. Keys are not stored in plaintext and can not be recovered after creation time.
    #[serde(rename = "api_key", deserialize_with = "Option::deserialize")]
    pub api_key: Option<String>,
    /// The date that the API key was created.
    #[serde(rename = "date_created")]
    pub date_created: String,
    /// The date that the API key will automatically expire.
    #[serde(rename = "date_expires", deserialize_with = "Option::deserialize")]
    pub date_expires: Option<String>,
    /// The last time that the API key was used to authenticate with the API.
    #[serde(rename = "date_last_used", deserialize_with = "Option::deserialize")]
    pub date_last_used: Option<String>,
    /// The database ID for the API key. Used when deleting keys.
    #[serde(rename = "id")]
    pub id: String,
    /// The human-readable name for the API key used for managing keys.
    #[serde(rename = "name")]
    pub name: String,
    /// The non-secret key prefix.
    #[serde(rename = "prefix")]
    pub prefix: String,
    /// The non-secret key suffix. Helpful for identifying keys if a name wasn't specified at creation time.
    #[serde(rename = "suffix")]
    pub suffix: String,
}

impl ApiKeyResponse {
    /// Response containing an API key.  This key is used in conjunction with the APIKey model to authenticate users in the API.
    pub fn new(api_key: Option<String>, date_created: String, date_expires: Option<String>, date_last_used: Option<String>, id: String, name: String, prefix: String, suffix: String) -> ApiKeyResponse {
        ApiKeyResponse {
            api_key,
            date_created,
            date_expires,
            date_last_used,
            id,
            name,
            prefix,
            suffix,
        }
    }
}

