/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiKeyErrorResponse : Action: Attempt to fetch an API key with username and password. Error: User does not exist or password is incorrect.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyErrorResponse {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ApiKeyErrorResponse {
    /// Action: Attempt to fetch an API key with username and password. Error: User does not exist or password is incorrect.
    pub fn new(username: String) -> ApiKeyErrorResponse {
        ApiKeyErrorResponse {
            username,
            message: None,
        }
    }
}

