/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CircuitCreateInput : Client input when creating a circuit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CircuitCreateInput {
    /// An arbitrary mapping of metadata keys to string values. This can be used to track additional information about the circuit such as an ID from an external system.
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<std::collections::HashMap<String, String>>,
    /// Tags for a circuit.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl CircuitCreateInput {
    /// Client input when creating a circuit.
    pub fn new() -> CircuitCreateInput {
        CircuitCreateInput {
            meta: None,
            tags: None,
        }
    }
}
