/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CircuitDoesNotExistResponse : Action: Attempt to fetch a circuit with circuit_id. Error: A circuit with circuit_id does not exist.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CircuitDoesNotExistResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "exception_id", skip_serializing_if = "Option::is_none")]
    pub exception_id: Option<Box<models::ExceptionId>>,
    #[serde(rename = "circuit_id")]
    pub circuit_id: Box<models::CircuitId>,
    #[serde(rename = "message")]
    pub message: String,
}

impl CircuitDoesNotExistResponse {
    /// Action: Attempt to fetch a circuit with circuit_id. Error: A circuit with circuit_id does not exist.
    pub fn new(error: String, circuit_id: models::CircuitId, message: String) -> CircuitDoesNotExistResponse {
        CircuitDoesNotExistResponse {
            error,
            exception_id: None,
            circuit_id: Box::new(circuit_id),
            message,
        }
    }
}

