/*
 * Sindri Labs API
 *
 *  ## About [Sindri Labs](https://www.sindri.app/)' API simplifies the developer experience to enable fast and scalable zero-knowledge proof generation.  Front-End Dashboard: [https://sindri.app/login](https://sindri.app/login)  ## Documentation The [Sindri Documentation](https://sindri.app/docs) contains everything you need to get started!  ## Sindri Resources The [sindri-resources GitHub repo](https://github.com/Sindri-Labs/sindri-resources) contains contains resources and sample data for the Sindri API.  ## Using this Page This is a standard [OpenAPI (Swagger)](https://swagger.io/specification/) API documentation page. It provides detailed documentation for each endpoint.  This page enables easy prototyping via the \"Try it out\" feature!  Since all Sindri endpoints require a valid API Key, in order to use the \"Try it out\" feature for any endpoint in this documentation you must first obtain an API key. Do this in one of two ways: 1. Enter your username and password in the `/api/apikey/generate` endpoint of the **Authorization** section below. Use the API key returned in the `access` field of the response. 2. Obtain an API key from the Sindri Dashboard team \"Account Settings\".  After obtaining your API key, authorize your page session by entering your API Key in the `SindriAPIKeyBearerAuth` section, reached by clicking \"Authorize\" below.  Proving Backend Version: v1.0.36 
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CircuitStatusResponse : Response for getting circuit status.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CircuitStatusResponse {
    /// A unique identifier generated for the circuit. UUID4 format.
    #[serde(rename = "circuit_id", deserialize_with = "Option::deserialize")]
    pub circuit_id: Option<serde_json::Value>,
    #[serde(rename = "status")]
    pub status: crate::models::JobStatus,
    /// The job is finished processing and waiting/polling can be terminated.
    #[serde(rename = "finished_processing", deserialize_with = "Option::deserialize")]
    pub finished_processing: Option<serde_json::Value>,
}

impl CircuitStatusResponse {
    /// Response for getting circuit status.
    pub fn new(circuit_id: Option<serde_json::Value>, status: crate::models::JobStatus, finished_processing: Option<serde_json::Value>) -> CircuitStatusResponse {
        CircuitStatusResponse {
            circuit_id,
            status,
            finished_processing,
        }
    }
}


