/*
 * Sindri Labs API
 *
 *  ## About [Sindri Labs](https://www.sindri.app/)' API simplifies the developer experience to enable fast and scalable zero-knowledge proof generation.  Front-End Dashboard: [https://sindri.app/login](https://sindri.app/login)  ## Documentation The [Sindri Documentation](https://sindri.app/docs) contains everything you need to get started!  ## Sindri Resources The [sindri-resources GitHub repo](https://github.com/Sindri-Labs/sindri-resources) contains contains resources and sample data for the Sindri API.  ## Using this Page This is a standard [OpenAPI (Swagger)](https://swagger.io/specification/) API documentation page. It provides detailed documentation for each endpoint.  This page enables easy prototyping via the \"Try it out\" feature!  Since all Sindri endpoints require a valid API Key, in order to use the \"Try it out\" feature for any endpoint in this documentation you must first obtain an API key. Do this in one of two ways: 1. Enter your username and password in the `/api/apikey/generate` endpoint of the **Authorization** section below. Use the API key returned in the `access` field of the response. 2. Obtain an API key from the Sindri Dashboard team \"Account Settings\".  After obtaining your API key, authorize your page session by entering your API Key in the `SindriAPIKeyBearerAuth` section, reached by clicking \"Authorize\" below.  Proving Backend Version: v1.2.4
 *
 * The version of the OpenAPI document: v1.17.8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CircuitType : CircuitType choices
/// CircuitType choices
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CircuitType {
    #[serde(rename = "boojum")]
    Boojum,
    #[serde(rename = "circom")]
    Circom,
    #[serde(rename = "gnark")]
    Gnark,
    #[serde(rename = "halo2")]
    Halo2,
    #[serde(rename = "hermez")]
    Hermez,
    #[serde(rename = "jolt")]
    Jolt,
    #[serde(rename = "noir")]
    Noir,
    #[serde(rename = "plonky2")]
    Plonky2,
    #[serde(rename = "snarkvm")]
    Snarkvm,
    #[serde(rename = "sp1")]
    Sp1,
}

impl std::fmt::Display for CircuitType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Boojum => write!(f, "boojum"),
            Self::Circom => write!(f, "circom"),
            Self::Gnark => write!(f, "gnark"),
            Self::Halo2 => write!(f, "halo2"),
            Self::Hermez => write!(f, "hermez"),
            Self::Jolt => write!(f, "jolt"),
            Self::Noir => write!(f, "noir"),
            Self::Plonky2 => write!(f, "plonky2"),
            Self::Snarkvm => write!(f, "snarkvm"),
            Self::Sp1 => write!(f, "sp1"),
        }
    }
}

impl Default for CircuitType {
    fn default() -> CircuitType {
        Self::Boojum
    }
}
