/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CircuitInfoResponse : Response for getting circuit info.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CircuitInfoResponse {
    #[serde(rename="boojum")]
    Boojum(Box<models::BoojumCircuitInfoResponse>),
    #[serde(rename="circom")]
    Circom(Box<models::CircomCircuitInfoResponse>),
    #[serde(rename="halo2")]
    Halo2(Box<models::Halo2CircuitInfoResponse>),
    #[serde(rename="gnark")]
    Gnark(Box<models::GnarkCircuitInfoResponse>),
    #[serde(rename="jolt")]
    Jolt(Box<models::JoltCircuitInfoResponse>),
    #[serde(rename="noir")]
    Noir(Box<models::NoirCircuitInfoResponse>),
    #[serde(rename="plonky2")]
    Plonky2(Box<models::Plonky2CircuitInfoResponse>),
}

impl Default for CircuitInfoResponse {
    fn default() -> Self {
        Self::Boojum(Default::default())
    }
}


