/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CircuitType : CircuitType choices
/// CircuitType choices
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CircuitType {
    #[serde(rename = "boojum")]
    Boojum,
    #[serde(rename = "circom")]
    Circom,
    #[serde(rename = "gnark")]
    Gnark,
    #[serde(rename = "halo2")]
    Halo2,
    #[serde(rename = "jolt")]
    Jolt,
    #[serde(rename = "noir")]
    Noir,
    #[serde(rename = "plonky2")]
    Plonky2,

}

impl std::fmt::Display for CircuitType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Boojum => write!(f, "boojum"),
            Self::Circom => write!(f, "circom"),
            Self::Gnark => write!(f, "gnark"),
            Self::Halo2 => write!(f, "halo2"),
            Self::Jolt => write!(f, "jolt"),
            Self::Noir => write!(f, "noir"),
            Self::Plonky2 => write!(f, "plonky2"),
        }
    }
}

impl Default for CircuitType {
    fn default() -> CircuitType {
        Self::Boojum
    }
}

