/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CircuitStatusResponse : Response for getting circuit status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CircuitStatusResponse {
    /// A unique identifier generated for the circuit. UUID4 format.
    #[serde(rename = "circuit_id")]
    pub circuit_id: String,
    /// The status of the circuit job.
    #[serde(rename = "status")]
    pub status: models::JobStatus,
    /// The job is finished processing and waiting/polling can be terminated.
    #[serde(rename = "finished_processing")]
    pub finished_processing: bool,
}

impl CircuitStatusResponse {
    /// Response for getting circuit status.
    pub fn new(circuit_id: String, status: models::JobStatus, finished_processing: bool) -> CircuitStatusResponse {
        CircuitStatusResponse {
            circuit_id,
            status,
            finished_processing,
        }
    }
}

