/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CircuitInfoResponse : Response for getting circuit info.


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "")]
pub enum CircuitInfoResponse {
}



/// The development framework used to write the circuit. This is specified during creation in the included sindri.json file.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CircuitType {
    #[serde(rename = "plonky2")]
    Plonky2,
}

impl Default for CircuitType {
    fn default() -> CircuitType {
        Self::Plonky2
    }
}

