/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ComingSoonResponse : Response for NotImplementedError
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComingSoonResponse {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ComingSoonResponse {
    /// Response for NotImplementedError
    pub fn new() -> ComingSoonResponse {
        ComingSoonResponse {
            message: None,
        }
    }
}

