/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForgeInternalErrorResponse : Response for ForgeInternalError
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForgeInternalErrorResponse {
    #[serde(rename = "exception_id", skip_serializing_if = "Option::is_none")]
    pub exception_id: Option<Box<models::ExceptionId>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ForgeInternalErrorResponse {
    /// Response for ForgeInternalError
    pub fn new() -> ForgeInternalErrorResponse {
        ForgeInternalErrorResponse {
            exception_id: None,
            message: None,
        }
    }
}
