/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForgeValueErrorResponse : Response for ForgeValueError
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForgeValueErrorResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ForgeValueErrorResponse {
    /// Response for ForgeValueError
    pub fn new(error: String) -> ForgeValueErrorResponse {
        ForgeValueErrorResponse {
            error,
            message: None,
        }
    }
}

