/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForgeInternalErrorResponse : Response for ForgeInternalError
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForgeInternalErrorResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ForgeInternalErrorResponse {
    /// Response for ForgeInternalError
    pub fn new(error: String) -> ForgeInternalErrorResponse {
        ForgeInternalErrorResponse {
            error,
            message: None,
        }
    }
}

