/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobStatus : JobStatus choices
/// JobStatus choices
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobStatus {
    #[serde(rename = "Queued")]
    Queued,
    #[serde(rename = "In Progress")]
    InProgress,
    #[serde(rename = "Ready")]
    Ready,
    #[serde(rename = "Failed")]
    Failed,

}

impl std::fmt::Display for JobStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "Queued"),
            Self::InProgress => write!(f, "In Progress"),
            Self::Ready => write!(f, "Ready"),
            Self::Failed => write!(f, "Failed"),
        }
    }
}

impl Default for JobStatus {
    fn default() -> JobStatus {
        Self::Queued
    }
}

