/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JwtTokenErrorResponse : Action: Attempt to fetch a JWT token with username and password. Error: User does not exist or password is incorrect.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwtTokenErrorResponse {
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(rename = "exception_id", skip_serializing_if = "Option::is_none")]
    pub exception_id: Option<Box<models::ExceptionId>>,
    #[serde(rename = "username")]
    pub username: String,
}

impl JwtTokenErrorResponse {
    /// Action: Attempt to fetch a JWT token with username and password. Error: User does not exist or password is incorrect.
    pub fn new(username: String) -> JwtTokenErrorResponse {
        JwtTokenErrorResponse {
            detail: None,
            exception_id: None,
            username,
        }
    }
}

