/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NoirCircuitInfoResponse : Response for getting Noir circuit info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoirCircuitInfoResponse {
    /// A unique identifier generated for the circuit. UUID4 format.
    #[serde(rename = "circuit_id")]
    pub circuit_id: String,
    #[serde(rename = "circuit_name")]
    pub circuit_name: String,
    /// The name of the project. This can be used in place of circuit_id for proving. This is specified during creation in the included sindri.json file. If the project is renamed, this will be the new name of the project, not the original name that was included in the sindri.json file.
    #[serde(rename = "project_name")]
    pub project_name: String,
    /// The development framework used to write the circuit. This is specified during creation in the included sindri.json file.
    #[serde(rename = "circuit_type")]
    pub circuit_type: CircuitType,
    /// The UTC datetime the circuit was uploaded in ISO8601 format.
    #[serde(rename = "date_created")]
    pub date_created: String,
    /// Metadata keys and values for the circuit that were specified at creation time.
    #[serde(rename = "meta")]
    pub meta: std::collections::HashMap<String, String>,
    /// The number of proofs submitted for this circuit.
    #[serde(rename = "num_proofs", deserialize_with = "Option::deserialize")]
    pub num_proofs: Option<i32>,
    /// The proving scheme for this circuit. This is specified during creation in the included sindri.json file.
    #[serde(rename = "proving_scheme")]
    pub proving_scheme: String,
    /// Whether the circuit is public. Public circuits can be used by any user.
    #[serde(rename = "public")]
    pub public: bool,
    /// The status of the circuit job.
    #[serde(rename = "status")]
    pub status: models::JobStatus,
    /// The job is finished processing and waiting/polling can be terminated.
    #[serde(rename = "finished_processing")]
    pub finished_processing: bool,
    /// Tags for the circuit.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    /// The name of the team that owns this circuit.
    #[serde(rename = "team")]
    pub team: String,
    /// URL for the avatar image of the team that owns this circuit.
    #[serde(rename = "team_avatar_url")]
    pub team_avatar_url: String,
    /// The slug of the team that owns this circuit.
    #[serde(rename = "team_slug")]
    pub team_slug: String,
    /// Total compute time in ISO8601 format.
    #[serde(rename = "compute_time", deserialize_with = "Option::deserialize")]
    pub compute_time: Option<String>,
    /// Total compute time in seconds.
    #[serde(rename = "compute_time_sec", deserialize_with = "Option::deserialize")]
    pub compute_time_sec: Option<f64>,
    /// Detailed compute times for the circuit compilation.
    #[serde(rename = "compute_times", deserialize_with = "Option::deserialize")]
    pub compute_times: Option<serde_json::Value>,
    /// Total size of stored file(s) in bytes.
    #[serde(rename = "file_size", deserialize_with = "Option::deserialize")]
    pub file_size: Option<i32>,
    /// Queue time in ISO8601 format.
    #[serde(rename = "queue_time", deserialize_with = "Option::deserialize")]
    pub queue_time: Option<String>,
    /// Queue time in seconds.
    #[serde(rename = "queue_time_sec", deserialize_with = "Option::deserialize")]
    pub queue_time_sec: Option<f64>,
    /// The name of the uploaded circuit file. Note: the CLI and SDKs create a generic name when a directory is specified for upload.
    #[serde(rename = "uploaded_file_name")]
    pub uploaded_file_name: String,
    /// Boolean indicating whether this circuit has a smart contract verifier available.
    #[serde(rename = "has_smart_contract_verifier")]
    pub has_smart_contract_verifier: bool,
    /// Boolean indicating whether this circuit has a verification key available.
    #[serde(rename = "has_verification_key")]
    pub has_verification_key: bool,
    /// The verification key of this circuit.
    #[serde(rename = "verification_key", deserialize_with = "Option::deserialize")]
    pub verification_key: Option<serde_json::Value>,
    /// A list of runtime warnings with UTC timestamps.
    #[serde(rename = "warnings", deserialize_with = "Option::deserialize")]
    pub warnings: Option<Vec<String>>,
    /// The error message for a failed circuit upload.
    #[serde(rename = "error", deserialize_with = "Option::deserialize")]
    pub error: Option<String>,
    /// The number of opcodes in the intermediate representation.
    #[serde(rename = "acir_opcodes", deserialize_with = "Option::deserialize")]
    pub acir_opcodes: Option<i32>,
    /// The number of constraints with an instantiated proving backend in the circuit.
    #[serde(rename = "circuit_size", deserialize_with = "Option::deserialize")]
    pub circuit_size: Option<i32>,
    /// The elliptic curve over which the proving protocol takes place.
    #[serde(rename = "curve")]
    pub curve: String,
    /// The name of the circuit project specified in the included Nargo.toml file.
    #[serde(rename = "nargo_package_name")]
    pub nargo_package_name: String,
    /// The Noir frontend version tag.
    #[serde(rename = "noir_version")]
    pub noir_version: String,
}

impl NoirCircuitInfoResponse {
    /// Response for getting Noir circuit info.
    pub fn new(circuit_id: String, circuit_name: String, project_name: String, circuit_type: CircuitType, date_created: String, meta: std::collections::HashMap<String, String>, num_proofs: Option<i32>, proving_scheme: String, public: bool, status: models::JobStatus, finished_processing: bool, tags: Vec<String>, team: String, team_avatar_url: String, team_slug: String, compute_time: Option<String>, compute_time_sec: Option<f64>, compute_times: Option<serde_json::Value>, file_size: Option<i32>, queue_time: Option<String>, queue_time_sec: Option<f64>, uploaded_file_name: String, has_smart_contract_verifier: bool, has_verification_key: bool, verification_key: Option<serde_json::Value>, warnings: Option<Vec<String>>, error: Option<String>, acir_opcodes: Option<i32>, circuit_size: Option<i32>, curve: String, nargo_package_name: String, noir_version: String) -> NoirCircuitInfoResponse {
        NoirCircuitInfoResponse {
            circuit_id,
            circuit_name,
            project_name,
            circuit_type,
            date_created,
            meta,
            num_proofs,
            proving_scheme,
            public,
            status,
            finished_processing,
            tags,
            team,
            team_avatar_url,
            team_slug,
            compute_time,
            compute_time_sec,
            compute_times,
            file_size,
            queue_time,
            queue_time_sec,
            uploaded_file_name,
            has_smart_contract_verifier,
            has_verification_key,
            verification_key,
            warnings,
            error,
            acir_opcodes,
            circuit_size,
            curve,
            nargo_package_name,
            noir_version,
        }
    }
}
/// The development framework used to write the circuit. This is specified during creation in the included sindri.json file.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CircuitType {
    #[serde(rename = "noir")]
    Noir,
}

impl Default for CircuitType {
    fn default() -> CircuitType {
        Self::Noir
    }
}

