/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ObtainApikeyInput : Client input to obtain an API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObtainApikeyInput {
    /// Your account username.
    #[serde(rename = "username")]
    pub username: String,
    /// Your account password.
    #[serde(rename = "password")]
    pub password: String,
    /// A human readable name for your API key used to identify it when managing keys.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ObtainApikeyInput {
    /// Client input to obtain an API key.
    pub fn new(username: String, password: String) -> ObtainApikeyInput {
        ObtainApikeyInput {
            username,
            password,
            name: None,
        }
    }
}

