/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedProjectInfoResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::ProjectInfoResponse>,
    #[serde(rename = "count")]
    pub count: i32,
}

impl PagedProjectInfoResponse {
    pub fn new(items: Vec<models::ProjectInfoResponse>, count: i32) -> PagedProjectInfoResponse {
        PagedProjectInfoResponse {
            items,
            count,
        }
    }
}

