/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedProofInfoResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::ProofInfoResponse>,
    #[serde(rename = "count")]
    pub count: i32,
}

impl PagedProofInfoResponse {
    pub fn new(items: Vec<models::ProofInfoResponse>, count: i32) -> PagedProofInfoResponse {
        PagedProofInfoResponse {
            items,
            count,
        }
    }
}

