/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PasswordChangeInput : Client input to change their password.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordChangeInput {
    /// Old password.
    #[serde(rename = "old_password")]
    pub old_password: String,
    /// New password.
    #[serde(rename = "new_password")]
    pub new_password: String,
}

impl PasswordChangeInput {
    /// Client input to change their password.
    pub fn new(old_password: String, new_password: String) -> PasswordChangeInput {
        PasswordChangeInput {
            old_password,
            new_password,
        }
    }
}

