/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectSettingsInput : Client input to update project settings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectSettingsInput {
    /// Whether the project is public.
    #[serde(rename = "is_public", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<Option<bool>>,
    /// The name of the project.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl ProjectSettingsInput {
    /// Client input to update project settings.
    pub fn new() -> ProjectSettingsInput {
        ProjectSettingsInput {
            is_public: None,
            name: None,
        }
    }
}

