/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectListInput : Client input for filtering project list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectListInput {
    /// Return projects owned by this team.
    #[serde(
        rename = "team_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub team_name: Option<Option<String>>,
}

impl ProjectListInput {
    /// Client input for filtering project list.
    pub fn new() -> ProjectListInput {
        ProjectListInput { team_name: None }
    }
}
