/*
 * Sindri Labs API
 *
 *  ## About [Sindri Labs](https://www.sindri.app/)' API simplifies the developer experience to enable fast and scalable zero-knowledge proof generation.  Front-End Dashboard: [https://sindri.app/login](https://sindri.app/login)  ## Documentation The [Sindri Documentation](https://sindri.app/docs) contains everything you need to get started!  ## Sindri Resources The [sindri-resources GitHub repo](https://github.com/Sindri-Labs/sindri-resources) contains contains resources and sample data for the Sindri API.  ## Using this Page This is a standard [OpenAPI (Swagger)](https://swagger.io/specification/) API documentation page. It provides detailed documentation for each endpoint.  This page enables easy prototyping via the \"Try it out\" feature!  Since all Sindri endpoints require a valid API Key, in order to use the \"Try it out\" feature for any endpoint in this documentation you must first obtain an API key. Do this in one of two ways: 1. Enter your username and password in the `/api/apikey/generate` endpoint of the **Authorization** section below. Use the API key returned in the `access` field of the response. 2. Obtain an API key from the Sindri Dashboard team \"Account Settings\".  After obtaining your API key, authorize your page session by entering your API Key in the `SindriAPIKeyBearerAuth` section, reached by clicking \"Authorize\" below.  Proving Backend Version: v1.0.36 
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProjectInfoResponse : Response for getting project info.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectInfoResponse {
    /// The UTC datetime the project was created in ISO8601 format.
    #[serde(rename = "date_created", deserialize_with = "Option::deserialize")]
    pub date_created: Option<serde_json::Value>,
    /// Whether the project is public.
    #[serde(rename = "is_public", deserialize_with = "Option::deserialize")]
    pub is_public: Option<serde_json::Value>,
    #[serde(rename = "latest_circuit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latest_circuit: Option<Option<Box<crate::models::ProjectLatestCircuitResponse>>>,
    /// The name of the project.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    /// The number of proofs created for this project.
    #[serde(rename = "num_proofs", deserialize_with = "Option::deserialize")]
    pub num_proofs: Option<serde_json::Value>,
    /// A unique identifier generated for the project. UUID4 format.
    #[serde(rename = "project_id", deserialize_with = "Option::deserialize")]
    pub project_id: Option<serde_json::Value>,
    /// Tags for the project.
    #[serde(rename = "tags", deserialize_with = "Option::deserialize")]
    pub tags: Option<serde_json::Value>,
    /// The name of the team that owns this project.
    #[serde(rename = "team", deserialize_with = "Option::deserialize")]
    pub team: Option<serde_json::Value>,
    /// URL for the avatar image of the team that owns this project.
    #[serde(rename = "team_avatar_url", deserialize_with = "Option::deserialize")]
    pub team_avatar_url: Option<serde_json::Value>,
    /// The slug of the team that owns this project.
    #[serde(rename = "team_slug", deserialize_with = "Option::deserialize")]
    pub team_slug: Option<serde_json::Value>,
}

impl ProjectInfoResponse {
    /// Response for getting project info.
    pub fn new(date_created: Option<serde_json::Value>, is_public: Option<serde_json::Value>, name: Option<serde_json::Value>, num_proofs: Option<serde_json::Value>, project_id: Option<serde_json::Value>, tags: Option<serde_json::Value>, team: Option<serde_json::Value>, team_avatar_url: Option<serde_json::Value>, team_slug: Option<serde_json::Value>) -> ProjectInfoResponse {
        ProjectInfoResponse {
            date_created,
            is_public,
            latest_circuit: None,
            name,
            num_proofs,
            project_id,
            tags,
            team,
            team_avatar_url,
            team_slug,
        }
    }
}


