/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectDoesNotExistResponse : Action: Attempt to fetch a project with project_id. Error: A project matching project_id does not exist for the team.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectDoesNotExistResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "exception_id", skip_serializing_if = "Option::is_none")]
    pub exception_id: Option<Box<models::ExceptionId>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "project_id")]
    pub project_id: String,
}

impl ProjectDoesNotExistResponse {
    /// Action: Attempt to fetch a project with project_id. Error: A project matching project_id does not exist for the team.
    pub fn new(error: String, message: String, project_id: String) -> ProjectDoesNotExistResponse {
        ProjectDoesNotExistResponse {
            error,
            exception_id: None,
            message,
            project_id,
        }
    }
}

