/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectInfoResponse : Response for getting project info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectInfoResponse {
    /// The UTC datetime the project was created in ISO8601 format.
    #[serde(rename = "date_created")]
    pub date_created: String,
    /// Whether the project is public.
    #[serde(rename = "is_public")]
    pub is_public: bool,
    #[serde(rename = "latest_circuit", skip_serializing_if = "Option::is_none")]
    pub latest_circuit: Option<Box<models::ProjectLatestCircuitResponse>>,
    /// The name of the project.
    #[serde(rename = "name")]
    pub name: String,
    /// The number of proofs created for this project.
    #[serde(rename = "num_proofs", deserialize_with = "Option::deserialize")]
    pub num_proofs: Option<i32>,
    /// A unique identifier generated for the project. UUID4 format.
    #[serde(rename = "project_id")]
    pub project_id: String,
    /// Tags for the project.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    /// The name of the team that owns this project.
    #[serde(rename = "team")]
    pub team: String,
    /// URL for the avatar image of the team that owns this project.
    #[serde(rename = "team_avatar_url")]
    pub team_avatar_url: String,
    /// The slug of the team that owns this project.
    #[serde(rename = "team_slug")]
    pub team_slug: String,
}

impl ProjectInfoResponse {
    /// Response for getting project info.
    pub fn new(date_created: String, is_public: bool, name: String, num_proofs: Option<i32>, project_id: String, tags: Vec<String>, team: String, team_avatar_url: String, team_slug: String) -> ProjectInfoResponse {
        ProjectInfoResponse {
            date_created,
            is_public,
            latest_circuit: None,
            name,
            num_proofs,
            project_id,
            tags,
            team,
            team_avatar_url,
            team_slug,
        }
    }
}

