/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProofHistogramInput : Client input for filtering proof histograms.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofHistogramInput {
    /// The bin size in seconds.
    #[serde(rename = "bin_size", skip_serializing_if = "Option::is_none")]
    pub bin_size: Option<i32>,
    /// Limit to proofs created on/after this timezone-aware, ISO8601 formatted time.
    #[serde(rename = "start_time")]
    pub start_time: String,
    /// Limit to proofs created on/before this timezone-aware, ISO8601 formatted time. Defaults to now.
    #[serde(rename = "end_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<Option<String>>,
}

impl ProofHistogramInput {
    /// Client input for filtering proof histograms.
    pub fn new(start_time: String) -> ProofHistogramInput {
        ProofHistogramInput {
            bin_size: None,
            start_time,
            end_time: None,
        }
    }
}

