/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// ProofInput : An object mapping proof input variable names to their values. Can be a raw JSON object or a string serialized as JSON or TOML.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProofInput {
    Json(Value),    // For raw JSON objects
    String(String), // For serialized JSON/TOML strings
}

impl Default for ProofInput {
    fn default() -> Self {
        ProofInput::String(String::new())
    }
}

impl ProofInput {
    /// An object mapping proof input variable names to their values. Can be a raw JSON object or a string serialized as JSON or TOML.
    pub fn new() -> ProofInput {
        Default::default()
    }
}
