/*
 * Sindri Labs API
 *
 *  ## About [Sindri Labs](https://www.sindri.app/)' API simplifies the developer experience to enable fast and scalable zero-knowledge proof generation.  Front-End Dashboard: [https://sindri.app/login](https://sindri.app/login)  ## Documentation The [Sindri Documentation](https://sindri.app/docs) contains everything you need to get started!  ## Sindri Resources The [sindri-resources GitHub repo](https://github.com/Sindri-Labs/sindri-resources) contains contains resources and sample data for the Sindri API.  ## Using this Page This is a standard [OpenAPI (Swagger)](https://swagger.io/specification/) API documentation page. It provides detailed documentation for each endpoint.  This page enables easy prototyping via the \"Try it out\" feature!  Since all Sindri endpoints require a valid API Key, in order to use the \"Try it out\" feature for any endpoint in this documentation you must first obtain an API key. Do this in one of two ways: 1. Enter your username and password in the `/api/apikey/generate` endpoint of the **Authorization** section below. Use the API key returned in the `access` field of the response. 2. Obtain an API key from the Sindri Dashboard team \"Account Settings\".  After obtaining your API key, authorize your page session by entering your API Key in the `SindriAPIKeyBearerAuth` section, reached by clicking \"Authorize\" below.  Proving Backend Version: v1.0.36 
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProofInfoResponse : Response for getting proof info.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofInfoResponse {
    /// A unique identifier generated for the proof. UUID4 format.
    #[serde(rename = "proof_id", deserialize_with = "Option::deserialize")]
    pub proof_id: Option<serde_json::Value>,
    #[serde(rename = "circuit_name", deserialize_with = "Option::deserialize")]
    pub circuit_name: Option<serde_json::Value>,
    /// The name of the project associated with this proof.
    #[serde(rename = "project_name", deserialize_with = "Option::deserialize")]
    pub project_name: Option<serde_json::Value>,
    /// The circuit_id of the circuit associated with this proof. UUID4 format.
    #[serde(rename = "circuit_id", deserialize_with = "Option::deserialize")]
    pub circuit_id: Option<serde_json::Value>,
    #[serde(rename = "circuit_type")]
    pub circuit_type: crate::models::CircuitType,
    /// The UTC datetime the circuit was uploaded in ISO8601 format.
    #[serde(rename = "date_created", deserialize_with = "Option::deserialize")]
    pub date_created: Option<serde_json::Value>,
    /// Metadata keys and values for the proof that were specified at creation time.
    #[serde(rename = "meta", deserialize_with = "Option::deserialize")]
    pub meta: Option<::std::collections::HashMap<String, serde_json::Value>>,
    /// A boolean indicating whether an internal verification check occurred during the proof creation.
    #[serde(rename = "perform_verify", deserialize_with = "Option::deserialize")]
    pub perform_verify: Option<serde_json::Value>,
    #[serde(rename = "status")]
    pub status: crate::models::JobStatus,
    /// The job is finished processing and waiting/polling can be terminated.
    #[serde(rename = "finished_processing", deserialize_with = "Option::deserialize")]
    pub finished_processing: Option<serde_json::Value>,
    /// The status of proof verification.
    #[serde(rename = "verified", deserialize_with = "Option::deserialize")]
    pub verified: Option<serde_json::Value>,
    /// The name of the team that owns this proof.
    #[serde(rename = "team", deserialize_with = "Option::deserialize")]
    pub team: Option<serde_json::Value>,
    /// URL for the avatar image of the team that owns this proof.
    #[serde(rename = "team_avatar_url", deserialize_with = "Option::deserialize")]
    pub team_avatar_url: Option<serde_json::Value>,
    /// The slug of the team that owns this proof.
    #[serde(rename = "team_slug", deserialize_with = "Option::deserialize")]
    pub team_slug: Option<serde_json::Value>,
    /// The name of the team that owns the circuit associated with this proof.
    #[serde(rename = "circuit_team", deserialize_with = "Option::deserialize")]
    pub circuit_team: Option<serde_json::Value>,
    /// URL for the avatar image of the team that owns the circuit associated with this proof.
    #[serde(rename = "circuit_team_avatar_url", deserialize_with = "Option::deserialize")]
    pub circuit_team_avatar_url: Option<serde_json::Value>,
    /// The slug of the team that owns the circuit associated with this proof.
    #[serde(rename = "circuit_team_slug", deserialize_with = "Option::deserialize")]
    pub circuit_team_slug: Option<serde_json::Value>,
    /// Total compute time in ISO8601 format.
    #[serde(rename = "compute_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute_time: Option<Option<serde_json::Value>>,
    /// Total compute time in seconds.
    #[serde(rename = "compute_time_sec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute_time_sec: Option<Option<serde_json::Value>>,
    /// Detailed compute times for the proof generation.
    #[serde(rename = "compute_times", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute_times: Option<Option<serde_json::Value>>,
    /// Total size of stored file(s) in bytes.
    #[serde(rename = "file_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<Option<serde_json::Value>>,
    /// The succinct argument(s) of knowledge.
    #[serde(rename = "proof", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub proof: Option<Option<serde_json::Value>>,
    /// The public outputs of the circuit.
    #[serde(rename = "public", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public: Option<Option<serde_json::Value>>,
    /// Queue time in ISO8601 format.
    #[serde(rename = "queue_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue_time: Option<Option<serde_json::Value>>,
    /// Queue time in seconds.
    #[serde(rename = "queue_time_sec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue_time_sec: Option<Option<serde_json::Value>>,
    /// The proof and public formatted as calldata for the smart contract verifier.
    #[serde(rename = "smart_contract_calldata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub smart_contract_calldata: Option<Option<serde_json::Value>>,
    /// Boolean indicating whether this proof has smart contract calldata available.
    #[serde(rename = "has_smart_contract_calldata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_smart_contract_calldata: Option<Option<serde_json::Value>>,
    /// Boolean indicating whether this proof's circuit has a verification key available.
    #[serde(rename = "has_verification_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_verification_key: Option<Option<serde_json::Value>>,
    /// The verification key of this circuit.
    #[serde(rename = "verification_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verification_key: Option<Option<serde_json::Value>>,
    /// A list of runtime warnings with UTC timestamps.
    #[serde(rename = "warnings", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Option<serde_json::Value>>,
    /// The error message for a failed proof.
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<serde_json::Value>>,
}

impl ProofInfoResponse {
    /// Response for getting proof info.
    pub fn new(proof_id: Option<serde_json::Value>, circuit_name: Option<serde_json::Value>, project_name: Option<serde_json::Value>, circuit_id: Option<serde_json::Value>, circuit_type: crate::models::CircuitType, date_created: Option<serde_json::Value>, meta: Option<::std::collections::HashMap<String, serde_json::Value>>, perform_verify: Option<serde_json::Value>, status: crate::models::JobStatus, finished_processing: Option<serde_json::Value>, verified: Option<serde_json::Value>, team: Option<serde_json::Value>, team_avatar_url: Option<serde_json::Value>, team_slug: Option<serde_json::Value>, circuit_team: Option<serde_json::Value>, circuit_team_avatar_url: Option<serde_json::Value>, circuit_team_slug: Option<serde_json::Value>) -> ProofInfoResponse {
        ProofInfoResponse {
            proof_id,
            circuit_name,
            project_name,
            circuit_id,
            circuit_type,
            date_created,
            meta,
            perform_verify,
            status,
            finished_processing,
            verified,
            team,
            team_avatar_url,
            team_slug,
            circuit_team,
            circuit_team_avatar_url,
            circuit_team_slug,
            compute_time: None,
            compute_time_sec: None,
            compute_times: None,
            file_size: None,
            proof: None,
            public: None,
            queue_time: None,
            queue_time_sec: None,
            smart_contract_calldata: None,
            has_smart_contract_calldata: None,
            has_verification_key: None,
            verification_key: None,
            warnings: None,
            error: None,
        }
    }
}


