/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProofHistogramResponse : Response for producing proof histograms.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofHistogramResponse {
    /// The bin size in seconds.
    #[serde(rename = "bin_size")]
    pub bin_size: i32,
    /// A list of dictionaries in the format:</br>                 ```                  {                      'bin': '2021-01-01T00:00:00Z',                      'ready': 2,                      'failed': 1,                      'in_progress': 3,                      'queued': 4,                  }                  ```</br>                  where 'bin' is an ISO8601 timestamp indicating the start                  of the bin, and proof status keys (e.g. 'ready') indicating                  the number of proofs with that status in the bin.
    #[serde(rename = "data")]
    pub data: Vec<serde_json::Value>,
    /// The end of the histogram in timezone-aware ISO8601 format.
    #[serde(rename = "end_time")]
    pub end_time: String,
    /// The start of the histogram in timezone-aware ISO8601 format.
    #[serde(rename = "start_time")]
    pub start_time: String,
}

impl ProofHistogramResponse {
    /// Response for producing proof histograms.
    pub fn new(bin_size: i32, data: Vec<serde_json::Value>, end_time: String, start_time: String) -> ProofHistogramResponse {
        ProofHistogramResponse {
            bin_size,
            data,
            end_time,
            start_time,
        }
    }
}

