/*
 * Sindri Labs API
 *
 *  ## About [Sindri Labs](https://www.sindri.app/)' API simplifies the developer experience to enable fast and scalable zero-knowledge proof generation.  Front-End Dashboard: [https://sindri.app/login](https://sindri.app/login)  ## Documentation The [Sindri Documentation](https://sindri.app/docs) contains everything you need to get started!  ## Sindri Resources The [sindri-resources GitHub repo](https://github.com/Sindri-Labs/sindri-resources) contains contains resources and sample data for the Sindri API.  ## Using this Page This is a standard [OpenAPI (Swagger)](https://swagger.io/specification/) API documentation page. It provides detailed documentation for each endpoint.  This page enables easy prototyping via the \"Try it out\" feature!  Since all Sindri endpoints require a valid API Key, in order to use the \"Try it out\" feature for any endpoint in this documentation you must first obtain an API key. Do this in one of two ways: 1. Enter your username and password in the `/api/apikey/generate` endpoint of the **Authorization** section below. Use the API key returned in the `access` field of the response. 2. Obtain an API key from the Sindri Dashboard team \"Account Settings\".  After obtaining your API key, authorize your page session by entering your API Key in the `SindriAPIKeyBearerAuth` section, reached by clicking \"Authorize\" below.  Proving Backend Version: v1.2.2
 *
 * The version of the OpenAPI document: v1.17.6
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProofHistogramResponse : Response for producing proof histograms.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofHistogramResponse {
    /// The bin size in seconds.
    #[serde(rename = "bin_size")]
    pub bin_size: i32,
    /// A list of dictionaries in the format:</br>                 ```                  {                      'bin': '2021-01-01T00:00:00Z',                      'ready': 2,                      'failed': 1,                      'in_progress': 3,                      'queued': 4,                  }                  ```</br>                  where 'bin' is an ISO8601 timestamp indicating the start                  of the bin, and proof status keys (e.g. 'ready') indicating                  the number of proofs with that status in the bin.
    #[serde(rename = "data")]
    pub data: Vec<serde_json::Value>,
    /// The end of the histogram in timezone-aware ISO8601 format.
    #[serde(rename = "end_time")]
    pub end_time: String,
    /// The start of the histogram in timezone-aware ISO8601 format.
    #[serde(rename = "start_time")]
    pub start_time: String,
}

impl ProofHistogramResponse {
    /// Response for producing proof histograms.
    pub fn new(
        bin_size: i32,
        data: Vec<serde_json::Value>,
        end_time: String,
        start_time: String,
    ) -> ProofHistogramResponse {
        ProofHistogramResponse {
            bin_size,
            data,
            end_time,
            start_time,
        }
    }
}
