/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProofInput : An object mapping proof input variable names to their values. Can be a raw JSON object or a string serialized as JSON or TOML.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofInput {
}

impl ProofInput {
    /// An object mapping proof input variable names to their values. Can be a raw JSON object or a string serialized as JSON or TOML.
    pub fn new() -> ProofInput {
        ProofInput {
        }
    }
}

