/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProofStatusResponse : Response for getting proof status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofStatusResponse {
    /// A unique identifier generated for the proof. UUID4 format.
    #[serde(rename = "proof_id")]
    pub proof_id: String,
    /// The status of the proof job.
    #[serde(rename = "status")]
    pub status: models::JobStatus,
    /// The job is finished processing and waiting/polling can be terminated.
    #[serde(rename = "finished_processing")]
    pub finished_processing: bool,
}

impl ProofStatusResponse {
    /// Response for getting proof status.
    pub fn new(proof_id: String, status: models::JobStatus, finished_processing: bool) -> ProofStatusResponse {
        ProofStatusResponse {
            proof_id,
            status,
            finished_processing,
        }
    }
}

