/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProofCannotBeCreatedResponse : Action: Attempt to create a proof with invalid input. Error: The proof cannot be created with the given input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofCannotBeCreatedResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "exception_id", skip_serializing_if = "Option::is_none")]
    pub exception_id: Option<Box<models::ExceptionId>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ProofCannotBeCreatedResponse {
    /// Action: Attempt to create a proof with invalid input. Error: The proof cannot be created with the given input.
    pub fn new(error: String) -> ProofCannotBeCreatedResponse {
        ProofCannotBeCreatedResponse {
            error,
            exception_id: None,
            message: None,
        }
    }
}

