/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SmartContractVerifierResponse : Response providing the smart contract verifier code.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmartContractVerifierResponse {
    /// The smart contract verifier code.
    #[serde(rename = "contract_code", deserialize_with = "Option::deserialize")]
    pub contract_code: Option<String>,
}

impl SmartContractVerifierResponse {
    /// Response providing the smart contract verifier code.
    pub fn new(contract_code: Option<String>) -> SmartContractVerifierResponse {
        SmartContractVerifierResponse {
            contract_code,
        }
    }
}

