/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamDoesNotExistResponse : Action: Attempt to reference a team with team_name. Error: A team with team_name does not exist.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDoesNotExistResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "team_name")]
    pub team_name: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl TeamDoesNotExistResponse {
    /// Action: Attempt to reference a team with team_name. Error: A team with team_name does not exist.
    pub fn new(error: String, team_name: String, message: String) -> TeamDoesNotExistResponse {
        TeamDoesNotExistResponse {
            error,
            team_name,
            message,
        }
    }
}

