/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamDetail : Details about a team.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDetail {
    /// URL for the team's avatar image.
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
    /// The date that the team was created.
    #[serde(rename = "date_created")]
    pub date_created: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "id")]
    pub id: i32,
    /// Whether the team is a personal team.
    #[serde(rename = "is_personal")]
    pub is_personal: bool,
    /// The name of the team.
    #[serde(rename = "name")]
    pub name: String,
    /// The number of projects owned by the team.
    #[serde(rename = "num_projects")]
    pub num_projects: i32,
    /// The number of proofs submitted by the team.
    #[serde(rename = "num_proofs", deserialize_with = "Option::deserialize")]
    pub num_proofs: Option<i32>,
    /// Whether the team is a Sindri corporate team.
    #[serde(rename = "sindri_corporate")]
    pub sindri_corporate: bool,
    /// The slug for the team (used for routing).
    #[serde(rename = "slug")]
    pub slug: String,
    /// The URL for the team's website.
    #[serde(rename = "url")]
    pub url: String,
}

impl TeamDetail {
    /// Details about a team.
    pub fn new(
        avatar_url: String,
        date_created: String,
        description: String,
        id: i32,
        is_personal: bool,
        name: String,
        num_projects: i32,
        num_proofs: Option<i32>,
        sindri_corporate: bool,
        slug: String,
        url: String,
    ) -> TeamDetail {
        TeamDetail {
            avatar_url,
            date_created,
            description,
            id,
            is_personal,
            name,
            num_projects,
            num_proofs,
            sindri_corporate,
            slug,
            url,
        }
    }
}
