/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamDoesNotExistResponse : Action: Attempt to reference a team with team_name. Error: A team with team_name does not exist.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDoesNotExistResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "exception_id", skip_serializing_if = "Option::is_none")]
    pub exception_id: Option<Box<models::ExceptionId>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "team_name")]
    pub team_name: String,
}

impl TeamDoesNotExistResponse {
    /// Action: Attempt to reference a team with team_name. Error: A team with team_name does not exist.
    pub fn new(error: String, message: String, team_name: String) -> TeamDoesNotExistResponse {
        TeamDoesNotExistResponse {
            error,
            exception_id: None,
            message,
            team_name,
        }
    }
}
