/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamMemberDetail : Details about a team member.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMemberDetail {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl TeamMemberDetail {
    /// Details about a team member.
    pub fn new(email: String, username: String) -> TeamMemberDetail {
        TeamMemberDetail { email, username }
    }
}
