/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamMeResponse : Details about the currently authenticated team.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMeResponse {
    #[serde(rename = "team")]
    pub team: Box<models::TeamDetail>,
}

impl TeamMeResponse {
    /// Details about the currently authenticated team.
    pub fn new(team: models::TeamDetail) -> TeamMeResponse {
        TeamMeResponse {
            team: Box::new(team),
        }
    }
}

