/*
 * Sindri Labs API
 *
 *  ## About [Sindri Labs](https://www.sindri.app/)' API simplifies the developer experience to enable fast and scalable zero-knowledge proof generation. Front-End Dashboard: [https://sindri.app/login](https://sindri.app/login) ## Documentation The [Sindri Documentation](https://sindri.app/docs) contains everything you need to get started! ## Sindri Resources The [sindri-resources GitHub repo](https://github.com/Sindri-Labs/sindri-resources) contains contains resources and sample data for the Sindri API. ## Using this Page This is a standard [OpenAPI (Swagger)](https://swagger.io/specification/) API documentation page. It provides detailed documentation for each endpoint. This page enables easy prototyping via the \"Try it out\" feature! Since all Sindri endpoints require a valid API Key, in order to use the \"Try it out\" feature for any endpoint in this documentation you must first obtain an API key. Do this in one of two ways: 1. Enter your username and password in the `/api/apikey/generate` endpoint of the **Authorization** section below. Use the API key returned in the `access` field of the response. 2. Obtain an API key from the Sindri Dashboard team \"Account Settings\". After obtaining your API key, authorize your page session by entering your API Key in the `SindriAPIKeyBearerAuth` section, reached by clicking \"Authorize\" below. Proving Backend Version: v1.2.16
 *
 * The version of the OpenAPI document: v1.17.24-rc1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamDetail : Details about a team.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDetail {
    /// URL for the team's avatar image.
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
    /// The date that the team was created.
    #[serde(rename = "date_created")]
    pub date_created: String,
    #[serde(rename = "description")]
    pub description: String,
    /// The URL for the team's github account.
    #[serde(rename = "github_url")]
    pub github_url: String,
    #[serde(rename = "id")]
    pub id: i32,
    /// Whether the team is a personal team.
    #[serde(rename = "is_personal")]
    pub is_personal: bool,
    /// The name of the team.
    #[serde(rename = "name")]
    pub name: String,
    /// The number of projects owned by the team.
    #[serde(rename = "num_projects")]
    pub num_projects: i32,
    #[serde(rename = "num_proofs", deserialize_with = "Option::deserialize")]
    pub num_proofs: Option<i32>,
    /// Whether the team is a Sindri corporate team.
    #[serde(rename = "sindri_corporate")]
    pub sindri_corporate: bool,
    /// The slug for the team (used for routing).
    #[serde(rename = "slug")]
    pub slug: String,
    /// The URL for the team's Twitter account.
    #[serde(rename = "twitter_url")]
    pub twitter_url: String,
    /// The URL for the team's website.
    #[serde(rename = "url")]
    pub url: String,
}

impl TeamDetail {
    /// Details about a team.
    pub fn new(
        avatar_url: String,
        date_created: String,
        description: String,
        github_url: String,
        id: i32,
        is_personal: bool,
        name: String,
        num_projects: i32,
        num_proofs: Option<i32>,
        sindri_corporate: bool,
        slug: String,
        twitter_url: String,
        url: String,
    ) -> TeamDetail {
        TeamDetail {
            avatar_url,
            date_created,
            description,
            github_url,
            id,
            is_personal,
            name,
            num_projects,
            num_proofs,
            sindri_corporate,
            slug,
            twitter_url,
            url,
        }
    }
}
