/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamMembersResponse : Details about a team's members.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMembersResponse {
    #[serde(rename = "team_slug")]
    pub team_slug: String,
    #[serde(rename = "members")]
    pub members: Vec<models::TeamMemberDetail>,
}

impl TeamMembersResponse {
    /// Details about a team's members.
    pub fn new(team_slug: String, members: Vec<models::TeamMemberDetail>) -> TeamMembersResponse {
        TeamMembersResponse {
            team_slug,
            members,
        }
    }
}

