/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRefreshOutputSchema {
    #[serde(rename = "refresh")]
    pub refresh: String,
    #[serde(rename = "access", deserialize_with = "Option::deserialize")]
    pub access: Option<String>,
}

impl TokenRefreshOutputSchema {
    pub fn new(refresh: String, access: Option<String>) -> TokenRefreshOutputSchema {
        TokenRefreshOutputSchema {
            refresh,
            access,
        }
    }
}

