/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRefreshInputSchema {
    #[serde(rename = "refresh")]
    pub refresh: String,
}

impl TokenRefreshInputSchema {
    pub fn new(refresh: String) -> TokenRefreshInputSchema {
        TokenRefreshInputSchema {
            refresh,
        }
    }
}

