/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenObtainPairOutputSchema {
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "refresh")]
    pub refresh: String,
    #[serde(rename = "access")]
    pub access: String,
}

impl TokenObtainPairOutputSchema {
    pub fn new(username: String, refresh: String, access: String) -> TokenObtainPairOutputSchema {
        TokenObtainPairOutputSchema {
            username,
            refresh,
            access,
        }
    }
}
