/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationErrorResponse : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationErrorResponse {
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl ValidationErrorResponse {
    /// 
    pub fn new(location: String, message: String) -> ValidationErrorResponse {
        ValidationErrorResponse {
            location,
            message,
        }
    }
}

