/*
 * Sindri Labs API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationErrorResponse : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationErrorResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "exception_id", skip_serializing_if = "Option::is_none")]
    pub exception_id: Option<Box<models::ExceptionId>>,
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl ValidationErrorResponse {
    pub fn new(error: String, location: String, message: String) -> ValidationErrorResponse {
        ValidationErrorResponse {
            error,
            exception_id: None,
            location,
            message,
        }
    }
}

