cargo-features = ["edition2024"]

[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
funty = "2.0.0"
sindri = { path = "../../../sindri", features = ["sp1-v5"] }
sp1-sdk = "5.0.0"
tokio = { version = "1.0", features = ["full"] }
