#! /bin/bash

# Use the location of the script as the working directory.
cd "$(dirname "$0")"

# Download the most recent open api spec
wget https://sindri.app/api/openapi.json

# Generate the client
npx @openapitools/openapi-generator-cli@2.16.3 generate -i openapi.json -g rust -o ../openapi --additional-properties=supportMiddleware=true,packageName=sindri-openapi

# Move up to the project root.
cd ..

# Format the client.
rustfmt $(find ./openapi/ -name "*.rs")

# Apply all patches in the openapi/patches directory
for patch in openapi/patches/*.patch; do
    git apply "$patch"
done

# Replace the package section in Cargo.toml with fixed values
sed -i '1,/^\[dependencies\]/c\[package]\nname = "sindri-openapi"\ndescription = "An autogenerated, configurable Sindri API client used by the main Sindri package"\nreadme = "README.md"\nversion.workspace = true\nedition.workspace = true\nauthors.workspace = true\nhomepage.workspace = true\nrepository.workspace = true\nlicense.workspace = true\nkeywords.workspace = true\n\n[dependencies]' openapi/Cargo.toml

# Update reqwest-middleware version from ^0.3 to ^0.4
sed -i 's/reqwest-middleware = { version = "\^0\.3"/reqwest-middleware = { version = "\^0\.4"/g' openapi/Cargo.toml

# Move back into scripts and remove the spec files.
cd ./scripts/
rm openapi.json
