name: CI Workflows

on:
  push:
    branches: ["main"]
  pull_request:
    # Do not run on draft pull requests
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    # Do not run on draft pull requests
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy

      - name: Build
        run: cargo build --verbose

      - name: Run sindri unit tests
        run: cargo test --package sindri --lib --features sp1-v3 --verbose

      - name: Run sindri-cli unit tests
        run: cargo test --package sindri-cli --bin cargo-sindri --verbose
